### ISSUE TITLE
Change youtube:init:tags to youtube:init:pubchannel

### ISSUE THREAD

**Issue by Alfro** [teltek/PumukitYoutubeBundle#2]
Currently we have this command to initialize the youtube pub channel tag in PuMuKIT:

``` sh
$ php app/console youtube:init:tags --force
```

I propose to change the name with something more intuitive, like:

``` sh
$ php app/console youtube:init:pubchannel
```

This also makes the Commands more uniform with respect to other PuMuKIT bundles (See [PuMuKIT-MoodleBundle](https://github.com/teltek/PuMuKIT2-moodle-bundle/blob/master/Resources/doc/InstallationGuide.md#step-2-install-the-bundle))

**Comment by mreyk** [comment]
If you change this one, you should do the same with PodcastBundle:
https://github.com/campusdomar/PuMuKIT2/blob/master/src/Pumukit/PodcastBundle/Command/PodcastInitTagsCommand.php#L20
https://github.com/campusdomar/PuMuKIT2/blob/master/src/Pumukit/PodcastBundle/Command/PodcastInitItunesUTagsCommand.php#L22
